# Generated by Django 4.1.5 on 2023-02-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_address_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='Вершинина, 33', max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Томск', max_length=100),
        ),
    ]
