# Generated by Django 4.1.5 on 2023-04-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animal',
            new_name='Material',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Type',
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ('name',), 'verbose_name': 'Material', 'verbose_name_plural': 'Materials'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('name',), 'verbose_name': 'Type', 'verbose_name_plural': 'Types'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='animal',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='type',
        ),
    ]
