# Generated by Django 4.1.5 on 2023-04-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Coupon', 'verbose_name_plural': 'Coupons'},
        ),
    ]
